### ISSUE TITLE
.has-child-dropdown-show - serves no purpose

### ISSUE THREAD

**Issue by morrow95** [dallaslu/bootstrap-4-multi-level-dropdown#3]
Looking at the js in particular this : 

```
$.fn.dropdown = (function() {
    var $bsDropdown = $.fn.dropdown;
    return function(config) {
        if (typeof config === 'string' && config === 'toggle') { // dropdown toggle trigged
            $('.has-child-dropdown-show').removeClass('has-child-dropdown-show');
            $(this).closest('.dropdown').parents('.dropdown').addClass('has-child-dropdown-show');
        }
        var ret = $bsDropdown.call($(this), config);
        $(this).off('click.bs.dropdown'); // Turn off dropdown.js click event, it will call 'this.toggle()' internal
        return ret;
    }
})();
```
these two lines never happen nor serve any purpose as far as I can tell : 

```
$('.has-child-dropdown-show').removeClass('has-child-dropdown-show');
$(this).closest('.dropdown').parents('.dropdown').addClass('has-child-dropdown-show');
```

**Comment by dallaslu** [comment]
`$('[data-toggle="dropdown"]').dropdown('toggle')`

**Comment by morrow95** [comment]
Can you elaborate a little?  Removing the block causes the menus to no longer work properly, but I can watch the dom and never see `.has-child-dropdown-show` ever applied.  I'm trying to understand what this block of code is actually doing as you also reference it later with :

```
    $('.dropdown').on('hide.bs.dropdown', function(e) {
        if ($(this).is('.has-child-dropdown-show')) {
        	$(this).removeClass('has-child-dropdown-show');
            e.preventDefault();
        }
        e.stopPropagation();    // do not need pop in multi level mode
    });
```

**Comment by dallaslu** [comment]
The logic of Bootstrap dropdown is to close all others if the current dropdown is active.

So, the core idea of a multi-level dropdown is to close all but own parent dropdown  (and the parent's parent... etc) if the current dropdown is active .

This code does three things in total.

1. Add class `has-child-dropdown-show` to all parents when calling `.dropdown('toggle')`
2. Prevent bootstrap from calling the internal `toggle()` method, because we can't override it.
3. Remove class `has-child-dropdown-show` from a parent dropdown and stop it from being hidden before `hide.bs.dropdown`.

For a parent dropdown, it gets a class before one of its children is active, and after that its `hide.bs.dropdown` event is fired by Bootstrap **immediately**, so it loses the class again.

You can set a breakpoint on this line and watch dom again.
```javascript
$(this).removeClass('has-child-dropdown-show');
```
Maybe I should rename this class as 'a-one-time-get-out-of-jail-free-card'.

If you want to understand this hack, then the best way is to read the source code of dropdown.js.
